import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Niraj's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="description" />
        <title>Dating</title>
      </head>
      <body className={`${inter.className} container px-10 `}>
        <main>{children}</main>
        <header>
          <Navbar />
        </header>
      </body>
    </html>
  );
}
